src/Belraysa/BackendBundle/Entity/Concepto.php
<?php
/**
 * Created by PhpStorm.
 * User: Ro
 * Date: 07/10/2015
 * Time: 13:15
 */

namespace Belraysa\BackendBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;

/**
 * Belraysa\BackendBundle\Entity\Concepto
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"concepto" = "Concepto", "ena" = "ENA", "envio" = "Envio", "menaje" = "Menaje" })
 * @ORM\Entity(repositoryClass="Belraysa\BackendBundle\Repository\ConceptoRepository")
 */
class Concepto
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer", unique=true)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var datetime $fechaCreacion
     *
     * @ORM\Column(name="fechaCreacion", type="datetime", nullable=false)
     */
    private $fechaCreacion;

    /**
     * @var string $tipo
     *
     * @ORM\Column(name="tipo", type="string", nullable=false)
     */
    private $tipo;

    /**
     * @var string $estado
     *
     * @ORM\Column(name="estado", type="string", nullable=false)
     */
    private $estado;

    /**
     * @var string $sisgerCode
     *
     * @ORM\Column(name="sisgerCode", type="string", nullable=true)
     */
    private $sisgerCode;

    /**
     * @ORM\OneToMany(targetEntity="Belraysa\BackendBundle\Entity\Bulto", mappedBy="concepto",cascade={"all"})
     */
    private $bultos;

    /**
     * @ORM\ManyToOne(targetEntity="Belraysa\BackendBundle\Entity\Contenedor", inversedBy="conceptos")
     * @ORM\JoinColumn(name="contenedor", referencedColumnName="id")
     */
    private $contenedor;

    /**
     * @ORM\ManyToOne(targetEntity="Belraysa\BackendBundle\Entity\Client", inversedBy="remitenteConceptos")
     * @ORM\JoinColumn(name="remitente", referencedColumnName="id")
     */
    private $remitente;

    /**
     * @ORM\ManyToOne(targetEntity="Belraysa\BackendBundle\Entity\Client", inversedBy="consignadoConceptos")
     * @ORM\JoinColumn(name="consignado", referencedColumnName="id")
     */
    private $consignado;

    /**
     * @Assert\DateTime()
     * @ORM\Column(name="fechaHBL", type="datetime", nullable=true)
     */
    private $fechaHBL;

    /**
     * @ORM\ManyToOne(targetEntity="Belraysa\BackendBundle\Entity\Reply", inversedBy="conceptos")
     * @ORM\JoinColumn(name="expediente", referencedColumnName="id")
     */
    private $expediente;

    function __construct()
    {
        $this->bultos = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getConsignado()
    {
        return $this->consignado;
    }

    /**
     * @param mixed $consignado
     */
    public function setConsignado($consignado)
    {
        $this->consignado = $consignado;
    }

    /**
     * @return datetime
     */
    public function getFechaCreacion()
    {
        return $this->fechaCreacion;
    }

    /**
     * @param datetime $fechaCreacion
     */
    public function setFechaCreacion($fechaCreacion)
    {
        $this->fechaCreacion = $fechaCreacion;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getBultos()
    {
        return $this->bultos;
    }

    /**
     * @param mixed $bultos
     */
    public function setBultos($bultos)
    {
        $this->bultos = $bultos;
    }


    /**
     * @return mixed
     */
    public function getRemitente()
    {
        return $this->remitente;
    }

    /**
     * @param mixed $remitente
     */
    public function setRemitente($remitente)
    {
        $this->remitente = $remitente;
    }

    /**
     * @return string
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * @param string $tipo
     */
    public function setTipo($tipo)
    {
        $this->tipo = $tipo;
    }

    public function addBulto(Bulto $bulto)
    {
        if (!$this->hasBulto($bulto)) {
            $bulto->setConcepto($this);
            $this->bultos->add($bulto);
        }
    }

    public function removeBulto(Bulto $bulto)
    {
        if ($this->hasBulto($bulto)) {
            $this->bultos->removeElement($bulto);
            $bulto->setConcepto(null);
        }
    }

    public function hasBulto(Bulto $bulto)
    {
        return $this->bultos->contains($bulto);
    }

    /**
     * @return string
     */
    public function getSisgerCode()
    {
        return $this->sisgerCode;
    }

    /**
     * @param string $sisgerCode
     */
    public function setSisgerCode($sisgerCode)
    {
        $now = new \DateTime();
        $this->sisgerCode = $sisgerCode;
        foreach ($this->bultos as $bulto) {
            $bulto->setSisgerCode("BRS" . date_format($now, 'y'). str_pad($this->bultos->count(), 3, 0, STR_PAD_LEFT) . str_pad($this->id, 6, 0, STR_PAD_LEFT) . "-" . str_pad($bulto->getIndice(), 4, 0, STR_PAD_LEFT));
        }
    }

    public function getValorAduanal()
    {
        $valor = 0;
        foreach ($this->bultos as $bulto) {
            $valor += $bulto->getValorAduanal();
        }
        return $valor;
    }

    /**
     * @return mixed
     */
    public function getEnvio()
    {
        return $this->envio;
    }

    /**
     * @param mixed $envio
     */
    public function setEnvio($envio)
    {
        $this->envio = $envio;
    }


    public function getMercancias()
    {
        $mercancias = array();
        foreach ($this->bultos as $bulto) {
            foreach ($bulto->getMercancias() as $mercancia) {
                $mercancias[] = $mercancia;
            }
        }
        return $mercancias;
    }

    /**
     * @return mixed
     */
    public function getContenedor()
    {
        return $this->contenedor;
    }

    /**
     * @param mixed $contenedor
     */
    public function setContenedor($contenedor)
    {
        $this->contenedor = $contenedor;
    }

    /**
     * @return string
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * @param string $estado
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;
    }

    public function getPesoKg()
    {
        $valor = 0;
        foreach ($this->bultos as $bulto) {
            $valor += $bulto->getPesoKg();
        }
        return $valor;
    }

    /**
     * @return int
     */
    public function getVolumenM3()
    {
        $valor = 0;
        foreach ($this->bultos as $bulto) {
            $valor += $bulto->getVolumenM3();
        }
        return $valor;
    }

    function __toString()
    {
        return $this->sisgerCode;
    }

    /**
     * @return mixed
     */
    public function getFechaHBL()
    {
        return $this->fechaHBL;
    }

    /**
     * @param mixed $fechaHBL
     */
    public function setFechaHBL($fechaHBL)
    {
        $this->fechaHBL = $fechaHBL;
    }

    public function getExpediente()
    {
        return $this->expediente;
    }

    public function setExpediente($expediente)
    {
        $this->expediente = $expediente;
    }

}

src/Belraysa/BackendBundle/Controller/ConceptoController.php
<?php

namespace Belraysa\BackendBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Belraysa\BackendBundle\Entity\Concepto;
use Belraysa\BackendBundle\Form\ConceptoType;

/**
 * Concepto controller.
 *
 */
class ConceptoController extends Controller
{

    /**
     * Lists all Concepto entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('BackendBundle:Concepto')->findAll();

        return $this->render('BackendBundle:Concepto:index.html.twig', array(
            'entities' => $entities,
        ));
    }

    public function indexByContenedorAction($contenedor)
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('BackendBundle:Concepto')->findByContenedor($contenedor);

        return $this->render('BackendBundle:Concepto:index.html.twig', array(
            'entities' => $entities,
            'contenedor' => $contenedor,
        ));
    }

    /**
     * Creates a new Concepto entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity = new Concepto();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('concepto_show', array('id' => $entity->getId())));
        }

        return $this->render('BackendBundle:Concepto:new.html.twig', array(
            'entity' => $entity,
            'form' => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Concepto entity.
     *
     * @param Concepto $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Concepto $entity)
    {
        $form = $this->createForm(new ConceptoType(), $entity, array(
            'action' => $this->generateUrl('concepto_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Concepto entity.
     *
     */
    public function newAction()
    {
        $entity = new Concepto();
        $form = $this->createCreateForm($entity);

        return $this->render('BackendBundle:Concepto:new.html.twig', array(
            'entity' => $entity,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Concepto entity.
     *
     */
    public function showAction()
    {
        $em = $this->getDoctrine()->getManager();
        $id = $_GET['id'];
        $entity = $em->getRepository('BackendBundle:Concepto')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Concepto entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BackendBundle:Concepto:show.html.twig', array(
            'entity' => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Concepto entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BackendBundle:Concepto')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Concepto entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('BackendBundle:Concepto:edit.html.twig', array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Creates a form to edit a Concepto entity.
     *
     * @param Concepto $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Concepto $entity)
    {
        $form = $this->createForm(new ConceptoType(), $entity, array(
            'action' => $this->generateUrl('concepto_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }

    /**
     * Edits an existing Concepto entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BackendBundle:Concepto')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Concepto entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('concepto_edit', array('id' => $id)));
        }

        return $this->render('BackendBundle:Concepto:edit.html.twig', array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a Concepto entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('BackendBundle:Concepto')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Concepto entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('concepto'));
    }

    /**
     * Creates a form to delete a Concepto entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('concepto_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm();
    }

    public function hblAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BackendBundle:Concepto')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Concepto entity.');
        }

        if ($entity->getTipo() == 'Envio') {
            $exporter = $entity->getRemitenteNombre();
        } else {
            $exporter = $entity->getRemitente()->getFirstName() . ' ' . $entity->getRemitente()->getLastName();
        }
        if ($entity->getConsignado()->getDni()) {
            $consigned = $entity->getConsignado()->getFirstName() . ' ' . $entity->getConsignado()->getLastName() . ', ' . $entity->getConsignado()->getDni();
        } else {
            $consigned = $entity->getConsignado()->getFirstName() . ' ' . $entity->getConsignado()->getLastName();
        }
        if ($entity->getFechaHBL()) {
            $dia = date_format($entity->getFechaHBL(), 'd');
            $mes = date_format($entity->getFechaHBL(), 'm');
            $anno = date_format($entity->getFechaHBL(), 'Y');
        } else {
            $dia = '';
            $mes = '';
            $anno = '';
        }
        $mbl = '';
        $origen = '';
        $destino = '';
        $motonave = '';
        $contenedor = '';
        if ($entity->getContenedor()) {
            $mbl = $entity->getContenedor()->getMbl();
            $origen = $entity->getContenedor()->getPuertoSalida();
            $destino = $entity->getContenedor()->getPuertoEntrada();
            $motonave = $entity->getContenedor()->getMotonave();

            $codigoContenedor = $entity->getContenedor()->getCodigo();
            $sello = $entity->getContenedor()->getSello();
            $dirContenedor = array();
            if ($codigoContenedor) {
                $dirContenedor[] = $codigoContenedor;
            }
            if ($sello) {
                $dirContenedor[] = $sello;
            }

            for ($j = 0; $j < sizeof($dirContenedor); $j++) {
                if ($j == 0) {
                    $contenedor = $contenedor . $dirContenedor[$j];
                } else {
                    $contenedor = $contenedor . ', ' . $dirContenedor[$j];
                }
            }
        }

        $address = $entity->getConsignado()->getAddress();
        $municipality = $entity->getConsignado()->getMunicipality();
        $province = $entity->getConsignado()->getProvince();
        $country = $entity->getConsignado()->getCountry();
        $telefono = $entity->getConsignado()->getPhones();
        $cell = $entity->getConsignado()->getCell();
        $dirArray = array();
        if ($address) {
            $dirArray[] = $address;
        }
        if ($municipality) {
            $dirArray[] = $municipality;
        }
        if ($province) {
            $dirArray[] = $province;
        }
        if ($country) {
            $dirArray[] = $country;
        }
        if ($telefono) {
            $dirArray[] = $telefono;
        }
        if ($cell) {
            $dirArray[] = $cell;
        }


        $direccion = '';
        for ($j = 0; $j < sizeof($dirArray); $j++) {
            if ($j == 0) {
                $direccion = $direccion . $dirArray[$j];
            } else {
                $direccion = $direccion . ', ' . $dirArray[$j];
            }
        }


        $code = $entity->getSisgerCode();

        $i = 0;

src/Belraysa/BackendBundle/Resources/views/Concepto/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Concepto edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('concepto') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Belraysa/BackendBundle/Resources/views/Concepto/index.html.twig
{% extends "BackendBundle::layout.html.twig" %}
{% block stylesheets_inline %}
    <link rel="stylesheet"
          href="{{ asset('bundles/backend/lte/plugins/datatables/dataTables.bootstrap.css') }}"
          xmlns="http://www.w3.org/1999/html">
    <link rel="stylesheet"
          href="{{ asset('bundles/backend/lte/plugins/tree/dist/themes/default/style.min.css') }}"
          xmlns="http://www.w3.org/1999/html">
    <link rel="stylesheet" href="{{ asset('bundles/backend/lte/plugins/iCheck/all.css') }}">

    <link rel="stylesheet"
          href="{{ asset('bundles/backend/lte/plugins/toastr-master/build/toastr.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/backend/lte/plugins/select2/dist/css/select2.min.css') }}">
    <link href="{{ asset('bundles/backend/lte/plugins/datepicker/datepicker3.css') }}" type="text/css" rel="stylesheet"
          xmlns="http://www.w3.org/1999/html"/>

{% endblock %}

{% block title %}HBLS{% endblock %}
{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                HBLS
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ path('index') }}"><i class="fa fa-home"></i> Inicio</a></li>
                <li>L-BRS</li>
                <li class="active">HBLS</li>
            </ol>
        </section>
        <br>
        <section class="content">

            <div class="row">
                <table class="table table-hover" id="datatable">
                    <thead>
                    <tr>
                        <th>C&oacute;digo</th>
                        <th>Remitente</th>
                        <th>Fecha Entrada</th>
                        <th>Fecha Salida</th>
                        <th>Cant. mercanc&iacute;as</th>
                        <th style="text-align: center">
                            <div class="mailbox-controls">
                              Acciones
                            </div>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for concepto in entities %}
                        <tr>
                            <td>
                                <img alt="*{{ concepto.sisgerCode }}*"
                                     src="{{ path('mercancia_barcode', { 'id': concepto.sisgerCode,  'size': 20 }) }}"/>
                            </td>
                            {#los [] al final es para q en el servidor me lo tome como un arreglo y poder hacer todas las acciones de busqueda etc#}
                            <td>{{ concepto.remitente.firstName }} {{ concepto.remitente.lastName }}</td>

                            <td>
                                {{ concepto.fechaEntrada|date('d/M/Y') }}
                            </td>
                            <td>
                                {{ concepto.fechaSalida|date('d/M/Y') }}
                            </td>
                            <td>
                                {{ concepto.mercancias|length }}
                            </td>

                            <td style="text-align: center">
                                <div class="mailbox-controls">
                                    <div class="btn-group">
                                        <a title="Ver mercanc&iacute;as" id="show_button"
                                           type="button"

                                           href="{{ path('mercancia', { 'concepto': concepto.id }) }}"
                                           class="btn btn-flat btn-default btn-sm"><i
                                                    class="fa fa-dropbox"></i>
                                        </a>
                                        <a title="Obtener HBL" id="hbl_button"
                                           type="button"
                                           href="{{ path('concepto_hbl', { 'id': concepto.id }) }}"
                                           class="btn btn-flat btn-sm btn-success"><i
                                                    class="fa fa-file-excel-o"></i>&nbsp;&nbsp;HBL
                                        </a>

                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.col -->

            <!-- /.row -->
        </section>

    </div><!-- /.content-wrapper -->



    <div class="modal fade" id="myModalHorizontal1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <button type="button" class="close"
                            data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="putYourTitleHere">

                    </h4>
                </div>

                <!-- Modal Body -->
                <div id="putContentHere" class="modal-body">
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <div id="putYourFooterHere">

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript_inline %}

    <script type="text/javascript" charset="utf8"
            src="{{ asset('bundles/backend/lte/plugins/datatables/jquery.dataTables.js') }}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{ asset('bundles/backend/lte/plugins/datatables/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('bundles/backend/lte/plugins/iCheck/icheck.min.js') }}"></script>
    <script src="{{ asset('bundles/backend/lte/plugins/PopConfirm-master/jquery.popconfirm.js') }}"></script>
    <script src="{{ asset('bundles/backend/lte/plugins/toastr-master/toastr.js') }}"></script>
    <script src="{{ asset('bundles/backend/lte/plugins/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('bundles/backend/lte/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
    <script type="text/javascript" charset="utf8"
            src="{{ asset('bundles/backend/js/enas.js') }}"></script>
    <script>
        $(".item-tree").removeClass("active");
        $("#contenedores").addClass("active");
        $('#datatable').DataTable(
            {
                "columns": [
                    {"orderable": false},
                    null,
                    null,
                    null,
                    null,
                    {"orderable": false}
                ]
            }
        );
    </script>
    <script>
        {% for flashMessage in app.session.flashbag.get('danger') %}
        lanzarError("{{ flashMessage }}");
        {% endfor %}
        {% for flashMessage in app.session.flashbag.get('success') %}
        lanzarOk("{{ flashMessage }}");
        {% endfor %}


    </script>
{% endblock %}

src/Belraysa/BackendBundle/Resources/views/Concepto/new.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Concepto creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('concepto') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/Belraysa/BackendBundle/Resources/views/Concepto/show.html.twig
<div class="tiles">
    {% set globalVA = 0 %}
    {% set globalPeso = 0 %}
    {% set globalVol = 0 %}
    {% set globalBultos = 0 %}

    <div>
        <label><b>{{ entity.getConsignado().getFirstName ~ ' ' ~ entity.getConsignado().getLastName }}</b></label> <label> <b> - {{ entity.getTipo() }} </b></label>
    </div>

    <div class="table-responsive" style="margin-top: 10px;">
        <table class="table table-striped table-bordered table-advance table-hover" id="table" style="margin-bottom: 0 !important">
            <thead>
            <tr>
                <th>Descripci&oacute;n</th>
                <th>Volumen (m3)</th>
                <th>Peso (Kgs)</th>
                <th>Relaci&oacute;n (Kgs/m3)</th>
                <th style="text-align: center">Valor Aduanal (VA)</th>
            </tr>
            </thead>
            <tbody>
            {% for bulto in entity.bultos %}
                {% for m in bulto.mercancias %}
                    {% set globalPeso = globalPeso + m.getPesoKg() %}
                    {% set globalVol = globalVol + m.getVolumenM3() %}
                    {% if(not m.miRelacionada) %}
                        {% set globalVA = globalVA + m.arancel.arancel %}
                    {% endif %}
                    <tr>
                        <td>{{ m.descripcion }}</td>
                        <td>
                            {{ m.volumenM3 }}
                        </td>

                        <td>
                            {{ m.pesoKg }}
                        </td>
                        <td>
                            {{ m.relacion }}
                        </td>
                        <td style="text-align: center">
                            {% if(m.miRelacionada) %}
                                0
                            {% else %}
                                {{ m.arancel.arancel }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                {% set globalBultos = globalBultos + 1 %}
            {% endfor %}
            </tbody>
            <thead>
                <tr>
                    <th>Totales</th>
                    <th>{{ globalVol }}</th>
                    <th>{{ globalPeso }}</th>
                    <th></th>
                    {% if(globalVA > 950) %}
                        <th style="text-align: center; color: red">{{ globalVA }}</th>
                    {% else %}
                        <th style="text-align: center">{{ globalVA }}</th>
                    {% endif %}
                </tr>
            </thead>
        </table>
    </div>

    {% if(globalVA > 950) %}
        <label style="color: red; margin-bottom: 15px; display: block">Se excedieron los 950 puntos de valor aduanal. Si esto no es lo deseado elimine alguna mercanc&iacute;a.</label>
    {% else %}
        <label style="color: red; margin-bottom: 15px; display: block; visibility: hidden">Se excedieron los 950 puntos de valor aduanal. Si esto no es lo deseado elimine alguna mercanc&iacute;a.</label>
    {% endif %}

    {% if entity.estado == 'HBL' %}
        <a style="color: white" href="{{ path('concepto_hbl', {'id': entity.id}) }}">
            <div title="Exportar HBL" class="tile bg-red" style="height: 145px; width: 145px !important">
                <div class="tile-body">
                    <label style="margin-bottom: 0">Bultos: {{ globalBultos }}</label>
                    <label style="margin-bottom: 0">Peso: {{ globalPeso }} kg</label>
                    <label style="margin-bottom: 0">Vol: {{ globalVol }} m3</label>
                </div>
                <div class="tile-object">
                    <div class="name">
                        <i class="fa fa-file" style="display:inline-block; font-size:large; width:20px"></i>HBL
                    </div>
                    <div class="number">

                    </div>
                </div>
            </div>
        </a>
    {% endif %}

    {% for bulto in entity.bultos %}
        {% set totalPeso = 0 %}
        {% set totalVol = 0 %}
        {% set desc = '' %}
        {% set descTitle = '' %}

        {% for m in bulto.mercancias %}
        {% set totalPeso = totalPeso + m.getPesoKg() %}
        {% set totalVol = totalVol + m.getVolumenM3() %}
        {% set desc = desc ~ m.getDescripcion() ~ '. ' %}
    {% endfor %}

        {% set descTitle = desc %}
        
        {% if desc|length > 12 %}
            {% set desc = desc[:13] ~ ' ' ~ desc[13:] %}
        {% endif %}
        {% if desc|length > 24 %}
            {% set desc = desc[:26] ~ ' ' ~ desc[26:] %}
        {% endif %}
        {% if desc|length > 36 %}
            {% set desc = desc[:39] ~ ' ' ~ desc[39:] %}
        {% endif %}

        {% if desc|length > 52 %}
            {% set desc = desc[:50] ~ '...' %}
        {% endif %}

        <a style="color: white" href="{{ path('bulto_etiqueta') }}?id={{ bulto.id }}">
            <div title="Exportar etiqueta" class="tile bg-green" style="height: 145px; width: 145px !important">
                <div class="tile-body">
                    <label style="margin-bottom: 0">Peso: {{ totalPeso }} kg</label>
                    <label style="margin-bottom: 0">Vol: {{ totalVol }} m3</label>
                    <label title="{{ descTitle }}" style="margin-bottom: 0"> {{ desc }}</label>
                </div>
            </div>
        </a>
    {% endfor %}

</div>